apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-dep-3
  labels:
    app: nginx
spec:
  replicas: 3
  strategy:
   type: RollingUpdate
   rollingUpdate:
     maxSurge: 1
     maxUnavailable: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        livenessProbe:
          periodSeconds: 10
          initialDelaySeconds: 20
          httpGet:
            path: /
            port: 80
        readinessProbe:
          periodSeconds: 10
          initialDelaySeconds: 20
          httpGet:
            path: /ready
            port: 80
        